/**
	Generated by sails-inverse-model
	Date:Tue Jul 10 2018 06:32:59 GMT+0100 (WAT)
*/

module.exports = {
  attributes: {
    name: {
      type: 'String',
      unique: true,
      required: true
    },
    configuration: {
      model: 'ClientConfiguration',
      required: true
    },
    visible: {
      type: 'boolean',
      defaultsTo: true
    }

  }
};
