/**
	Generated by sails-inverse-model
	Date:Tue Jul 10 2018 06:32:59 GMT+0100 (WAT)
*/

module.exports = {
  attributes: {
    name: {
      type: 'String',
      required: true
    },

    base_interest_rate: {
      type: 'number',
      required: true
    },

    client_profit_percent: {
      type: 'number',
      required: true
    },

    minimum_duration: {
      type: 'number',
      required: true
    },

    maximum_interest_rate: {
      type: 'number',
      required: true
    },
    visible: {
      type: 'boolean',
      defaultsTo: true
    }

  }
};
