/**
	Generated by sails-inverse-model
	Date:Tue Jul 10 2018 06:32:59 GMT+0100 (WAT)
*/

module.exports = {
  attributes: {
    user: {
      model: 'ClientUser',
      required: true
    },
    amount: {
      type: 'number',
      required: true
    },

    interest_rate: {
      type: 'number',
      required: true
    },

    duration: {
      type: 'number',
      required: true
    },

    status: {
      model: 'CreditRequestStatus',
      required: true
    },
    visible: {
      type: 'boolean',
      defaultsTo: true
    }
  }
};
