/**
	Generated by sails-inverse-model
	Date:Tue Jul 10 2018 06:32:59 GMT+0100 (WAT)
*/

module.exports = {
  attributes: {

    creditor: {
      model: 'ClientUser',
      required: true
    },

    amount: {
      type: 'number',
      required: true
    },

    interest: {
      type: 'number',
      required: true
    },

    duration: {
      type: 'number',
      required: true
    },

    profit: {
      type: 'number',
      required: true
    },

    transaction: {
      model: 'Transaction',
      required: true
    },

    status: {
      model: 'CreditStatus',
      required: true
    },
    visible: {
      type: 'boolean',
      defaultsTo: true
    }
  }
};
