/**
	Generated by sails-inverse-model
	Date:Tue Jul 10 2018 06:32:59 GMT+0100 (WAT)
*/

module.exports = {
  attributes: {
    user: {
      model: 'ClientUser',
      required: true
    },

    credit_request: {
      model: 'CreditRequest',
      required: true
    },

    credit: {
      model: 'Credit',
      required: true
    },

    transaction: {
      model: 'Transaction'
    },

    duration: {
      type: 'number',
      required: true
    },
    status: {
      model: 'DebitStatus',
      required: true
    },
    visible: {
      type: 'boolean',
      defaultsTo: true
    }
  }
};
